# @MajoraGenerator({"force_generation": true})

dematimbre_rest_api_person_cget:
    path: /
    defaults:
        _controller: DematimbreApiCustomerBundle:PersonApi:cget
    methods:
        - GET

dematimbre_rest_api_person_create:
    path: /
    defaults:
        _controller: DematimbreApiCustomerBundle:PersonApi:post
    methods:
        - POST

dematimbre_rest_api_person_get:
    path: /{id}
    defaults:
        _controller: DematimbreApiCustomerBundle:PersonApi:get
    requirements:
        id: \d+
    methods:
        - GET

dematimbre_rest_api_person_put:
    path: /{id}
    defaults:
        _controller: DematimbreApiCustomerBundle:PersonApi:put
    requirements:
        id: \d+
    methods:
        - PUT
        - PATCH

dematimbre_rest_api_person_delete:
    path: /{id}
    defaults:
        _controller: DematimbreApiCustomerBundle:PersonApi:delete
    requirements:
        id: \d+
    methods:
        - DELETE
