# @MajoraGenerator({"include_routing": {"target": "../routing.yml"}})
# @MajoraGenerator({"include_routing": {"route": "dematimbre_admin_person"}})
# @MajoraGenerator({"include_routing": {"resource": "routing/person.yml"}})
# @MajoraGenerator({"include_routing": {"prefix": "/persons"}})

# generated routes
auto_dematimbre_admin_person:
    resource: "@DematimbreAdminCustomerBundle/Resources/config/routing/auto/auto_person.yml"
