# Ansible Galaxy requirements
#
# ansible-galaxy install --force --role-file=requirements.yml

- src: https://github.com/LinkValue/majora-ansible-playbook
  path: ansible
  name: roles

- src: rvm_io.rvm1-ruby
  path: ansible/roles
  name: ruby
