# @MajoraGenerator({"register_doctrine_em": {"em": "ddp_em"}})
# @MajoraGenerator({"register_doctrine_em": {"prefix": "Dematimbre\\Si\\Component\\Customer\\Entity"}})
# @MajoraGenerator({"register_doctrine_em": {"bundle": "DematimbreSiCustomerBundle"}})
# @MajoraGenerator({"register_doctrine_em": {"alias": "DematimbreSiCustomer"}})

Dematimbre\Si\Component\Customer\Entity\Person:
    type: entity
    repositoryClass: Dematimbre\Si\Component\Customer\Repository\Doctrine\PersonDoctrineRepository
    table: dematimbre_si_person
    actAs:
        Timestampable: ~
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firstname:
            type: string
        lastname:
            type: string
        email:
            type: string
        deviceToken:
            type: string
            column: device_token
            nullable: true

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    # manyToOne:
    #     example:
    #         targetEntity: Example
    #         inversedBy: persons
    #         joinColumn:
    #             name: example_id
    #             referencedColumnName: id

    # oneToMany:
    #     examples:
    #         targetEntity: Example
    #         mappedBy: person
    #         cascade: ['persist', 'remove']

    # manyToMany:
    #     examples:
    #         targetEntity: Example
    #         joinTable:
    #             name: dematimbre_person_example
    #             joinColumns:
    #                 person_id:
    #                     referencedColumnName: id
    #             inverseJoinColumns:
    #                 example_id:
    #                     referencedColumnName: id
