# @MajoraGenerator({"include_routing": {"target": "/config/routing/routing_api.yml"}})
# @MajoraGenerator({"include_routing": {"route": "dematimbre_api_majora_namespace"}})
# @MajoraGenerator({"include_routing": {"resource": "@DematimbreApiMajoraNamespaceBundle/Resources/config/routing.yml"}})
